<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
                </strong>
            </div>
            <!-- if Stefan_Flags module is enabled render list with flags, else render regular list  -->
            <?php if($this->helper('Stefan\Flags\Helper\Helper')->getConfig('stefan_flags/general/enable')){ ?>
                <ul class="dropdown switcher-dropdown"
                    data-target="dropdown">
                    <?php foreach ($block->getStores() as $_lang) : ?>
                        <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                            <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <?php $flag = $this->helper('Stefan\Flags\Helper\Helper')->getConfigById('stefan_flags/general/flags', $_lang->getId()); ?>
                                <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                    <?php if($_lang->getId() !== NULL){ ?>
                                        <img src='<?php echo $this->getViewFileUrl('Stefan_Flags::images/' . $flag . '.svg'); ?>' width="30" height="25">
                                    <?php } ?>
                                    <span><?= $block->escapeHtml($_lang->getName()) ?></span>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php }else{ ?>
                <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getStores() as $_lang) : ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul> 
            <?php } ?>
        </div>
    </div>
<?php endif; ?>
